apiVersion: v1
kind: List
items:
- kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    name: log-tester
  spec:
    template:
      metadata:
        labels:
          app: log-tester
      spec:
        containers:
        - name: log-tester
          image: "${imageName}"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 9
          livenessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 11
            timeoutSeconds: 2
          env:
          - name: INTERVAL
            value: "120"
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP
    replicas: ${replicas}
