apiVersion: v1
kind: Service
metadata:
  labels:
    app: log-tester
  name: log-tester
  namespace: ${k8sNamespace}
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '8080'
    prometheus.io/scrape: 'true'
    prometheus.io/scheme: http
spec:
  selector:
    app: log-tester
  ports:
  - name: myport
    port: 80
    protocol: TCP
    targetPort: 8080
  type: NodePort
